--- #YAML:1.0
name:                XML-RSS-PicLens
version:             0.02
abstract:            Create a PicLens compatible RSS feed
license:             perl
author:              
    - Andy Armstrong <andy.armstrong@messagesystems.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Data::Section:                 0.004
    Test::More:                    0
    Test::XML:                     0.07
    XML::RSS:                      1.33
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
